{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-nginx-dapi
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.nginxDapi.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx-declarative-api.nginxDapi.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.nginxDapi.containerPort }}
          protocol: TCP
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "nginx-declarative-api.redis.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Values.redis.containerPort }}
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              {{- include "nginx-declarative-api.devportal.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Values.devportal.containerPort }}
          protocol: TCP
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-redis
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.redis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx-declarative-api.redis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "nginx-declarative-api.nginxDapi.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Values.redis.containerPort }}
          protocol: TCP
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-devportal
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.devportal.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx-declarative-api.devportal.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "nginx-declarative-api.nginxDapi.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Values.devportal.containerPort }}
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
