{{- if and .Values.nginxDapi.enabled .Values.nginxDapi.persistence.enabled (not .Values.nginxDapi.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-nginx-dapi
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.nginxDapi.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.nginxDapi.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.nginxDapi.persistence.size }}
  {{- if .Values.nginxDapi.persistence.storageClass }}
  storageClassName: {{ .Values.nginxDapi.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- if and .Values.redis.enabled .Values.redis.persistence.enabled (not .Values.redis.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-redis
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- if and .Values.devportal.enabled .Values.devportal.persistence.enabled (not .Values.devportal.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-declarative-api.fullname" . }}-devportal
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.devportal.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.devportal.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.devportal.persistence.size }}
  {{- if .Values.devportal.persistence.storageClass }}
  storageClassName: {{ .Values.devportal.persistence.storageClass }}
  {{- end }}
{{- end }}
