{{- if .Values.nginxDapi.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-declarative-api.nginxDapi.serviceAccountName" . }}
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.nginxDapi.labels" . | nindent 4 }}
  {{- with .Values.nginxDapi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.nginxDapi.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if .Values.devportal.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-declarative-api.devportal.serviceAccountName" . }}
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.devportal.labels" . | nindent 4 }}
  {{- with .Values.devportal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.devportal.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if .Values.webui.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-declarative-api.webui.serviceAccountName" . }}
  namespace: {{ include "nginx-declarative-api.namespace" . }}
  labels:
    {{- include "nginx-declarative-api.webui.labels" . | nindent 4 }}
  {{- with .Values.webui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.webui.serviceAccount.automountServiceAccountToken }}
{{- end }}
