volumes:
  redis_data:

services:
  redis:
    image: redis
    container_name: "redis"
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - dapi-network
    volumes:
      - redis_data:/data:rw

  devportal:
    image: nginx-declarative-api-devportal
    build:
      context: ../devportal/redocly
      dockerfile: Dockerfile
    user: "${USERID}:${USERGROUP}"
    container_name: "devportal"
    restart: always
    ports:
      - "${DEVPORTAL_PORT:-5001}:5000"
    networks:
      - dapi-network

  nginx-dapi:
    image: nginx-declarative-api
    build:
      context: ../../
      dockerfile: Dockerfile
    user: "${USERID}:${USERGROUP}"
    container_name: "nginx-dapi"
    restart: always
    depends_on:
      - redis
    ports:
      - "${DAPI_PORT:-5000}:5000"
    networks:
      - dapi-network

networks:
  dapi-network:
